name: Before Merge

on:
  merge_group:

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Clean Build with Gradle
        run: ./gradlew clean build
