name: Validate PR

# https://github.com/orgs/community/discussions/51120#discussioncomment-8623798
on:
  workflow_dispatch:
  pull_request:

jobs:
  validate-pr:
    if: ${{ github.event_name != 'pull_request' }} # see the link above
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Clean Build with Gradle
        run: ./gradlew clean build
